name: flutter_animation
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/socials/facebook.png
   - assets/images/socials/groupme.png
   - assets/images/socials/instagram.png
   - assets/images/socials/itunes.png
   - assets/images/socials/kik.png
   - assets/images/socials/linkedin.png
   - assets/images/socials/messenger.png
   - assets/images/socials/periscope.png
   - assets/images/socials/reddit.png
   - assets/images/socials/skype.png
   - assets/images/socials/snapchat.png
   - assets/images/socials/tumblr.png
   - assets/images/socials/twitter.png
   - assets/images/socials/whatsapp.png
   - assets/images/socials/youtube.png
   

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700